server:
  port: 8080
  session-timeout: 60
 
spring:
    redis:
       database: 0
       host: 106.12.211.237
       port: 6379
       password:
       timeout: 0
       pool:
           max-active: 8
           max-wait: -1
           max-idle: 8
           min-idle: 0
    session:
      store-type: none
